plugin: amazon.aws.aws_ec2
strict: False
regions:
  - us-east-1
hostnames:
  - ip-address
filters:
  instance-state-name: running
  tag:Name:
    - jenkins_master
    - jenkins_slave
keyed_groups:
  - key: tags.Name
    prefix: tag
    separator: ""